/* ==========================================================
   V1 — Create base tables (matches local schema essentials)
   ========================================================== */

-- app_user
CREATE TABLE IF NOT EXISTS public.app_user (
                                               id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               email     VARCHAR(255),
    enabled   BOOLEAN NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    password  VARCHAR(255) NOT NULL,
    username  VARCHAR(255) NOT NULL
    );

-- role
CREATE TABLE IF NOT EXISTS public.role (
                                           id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           name VARCHAR(50) NOT NULL
    );

-- user_roles
CREATE TABLE IF NOT EXISTS public.user_roles (
                                                 user_id BIGINT NOT NULL,
                                                 role_id BIGINT NOT NULL
);

-- availability (one row per user + day_of_week)
CREATE TABLE IF NOT EXISTS public.availability (
                                                   id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                   day_of_week                VARCHAR(255) NOT NULL,
    dinner_available           BOOLEAN,
    lunch_available            BOOLEAN,
    user_id                    BIGINT NOT NULL,
    submitted_at               TIMESTAMP WITHOUT TIME ZONE,
    decided_at                 TIMESTAMP WITHOUT TIME ZONE,
    requested_lunch_available  BOOLEAN,
    requested_dinner_available BOOLEAN,
    status                     VARCHAR(20),
    CONSTRAINT availability_day_of_week_check CHECK (
                                                        day_of_week::text = ANY (
                                                        ARRAY['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY']::text[]
                                                                                                                                           )
    )
    );

-- shift (note: position is quoted in your schema)
CREATE TABLE IF NOT EXISTS public.shift (
                                            id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            date     DATE,
                                            period   VARCHAR(255),
    "position" VARCHAR(255),
    CONSTRAINT shift_period_check CHECK (
                                            period::text = ANY (ARRAY['LUNCH','DINNER']::text[])
    ),
    CONSTRAINT shift_position_check CHECK (
                                              "position"::text = ANY (
                                              ARRAY[
                                              'LUNCH_SERVER','LUNCH_ASSISTANT','LUNCH_MANAGER',
                                              'SERVER_1','SERVER_2','SERVER_3','SUSHI','EXPO',
                                              'BUSSER_1','BUSSER_2','HOST_1','HOST_2','FLOAT'
    ]::text[]
           )
    )
    );

-- assignment
CREATE TABLE IF NOT EXISTS public.assignment (
                                                 id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 user_id  BIGINT NOT NULL,
                                                 shift_id BIGINT NOT NULL
);
