/* ==========================================================
   V8 — Create employee table (required by Hibernate validation)
   ========================================================== */

CREATE TABLE IF NOT EXISTS employee (
                                        id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        active    BOOLEAN NOT NULL DEFAULT TRUE,
                                        email     VARCHAR(255),
    full_name VARCHAR(255) NOT NULL
    );

-- match local schema uniqueness expectation
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk_employee_email') THEN
    EXECUTE 'ALTER TABLE employee ADD CONSTRAINT uk_employee_email UNIQUE (email)';
END IF;
END
$$ LANGUAGE plpgsql;
